name: dicesapp
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  getflutter: ^1.0.11
  flutter_icons: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: PermanentMarker
      fonts:
        - asset: assets/fonts/PermanentMarker-Regular.ttf
    - family: LeckerliOne
      fonts:
        - asset: assets/fonts/LeckerliOne-Regular.ttf
    - family: Genesys
      fonts:
        - asset: assets/fonts/Genesys_Icons_05.ttf